### ISSUE TITLE
13.04.21

### ISSUE THREAD

**Issue by roykoand** [MixaKonan/Menhera#3]
1.  Ответ button is not work
2.  Problem with attach file window in Opera. When push 'закрити вспливаюче вікно' [ukr] (what maybe mean exit from this window, but it doesn't work).
3. I don't understand in which time zone site work.

# Я здавав фізику і ваші англійські мені нафік не здались

**Comment by roykoand** [comment]
4. Add readme file : )

**Comment by MixaKonan** [comment]
> 3. I don't understand in which time zone site work.

The data center is probably located in Denmark

Post time will be soon set to the client's time.

**Comment by MixaKonan** [comment]
"Ответ" button changed to "Перейти к посту". Post time is now displayed with the client's timezone offset.
